# Generated by Django 5.0.6 on 2024-07-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursType",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "civilite",
                    models.CharField(
                        choices=[("Madame", "Madame"), ("Monsieur", "Monsieur")],
                        default="Madame",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("phone_number", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enseignant", "Je suis enseignant(e) en activité"),
                            ("retraite", "Je suis enseignant(e) à la retraite"),
                            ("etudiant", "Je suis étudiant(e)"),
                            ("salarie", "Je suis salarié(e) ou indépendant(e)"),
                            ("autre", "J'ai un autre profil"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_bac_plus_trois", models.BooleanField(default=False)),
                (
                    "highest_degree_earned",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("cv", models.FileField(blank=True, null=True, upload_to="cvs/")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("levels", models.CharField(max_length=100)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                through="accounts.TeacherSubject", to="accounts.subject"
            ),
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("student", "Étudiant"),
                            ("child", "Élève"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("city_or_postal_code", models.CharField(max_length=100)),
                ("cours_types", models.ManyToManyField(to="accounts.courstype")),
                ("levels", models.ManyToManyField(to="accounts.level")),
                ("subjects", models.ManyToManyField(to="accounts.subject")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
