# Generated by Django 5.0.6 on 2024-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_subject_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
