# Generated by Django 5.0.6 on 2024-07-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_subject_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="cours_types",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="levels",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="subjects",
        ),
        migrations.AddField(
            model_name="visitor",
            name="level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.level",
            ),
        ),
        migrations.CreateModel(
            name="VisitorSubjectCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cours_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.courstype",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.subject",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_courses",
                        to="accounts.visitor",
                    ),
                ),
            ],
            options={
                "unique_together": {("visitor", "subject", "cours_type")},
            },
        ),
    ]
