# Generated by Django 5.0.6 on 2024-07-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_visitor_cours_types_remove_visitor_levels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorsubjectcourse",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_courses",
                to="accounts.teacher",
            ),
        ),
    ]
