# Generated by Django 5.0.6 on 2024-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monEspace", "0002_alter_note_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="embedding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
