# Generated by Django 5.0.6 on 2024-07-12 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monEspace", "0004_note_est_partagee_note_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="est_partagee",
        ),
        migrations.RemoveField(
            model_name="note",
            name="subject",
        ),
    ]
