# Generated by Django 5.0.6 on 2024-07-14 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_visitor_cours_types_remove_visitor_levels_and_more"),
        ("monEspace", "0005_remove_note_est_partagee_remove_note_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="accounts.visitorsubjectcourse",
            ),
        ),
    ]
